name: "RMX|7 Romy Elmaco Blog"
description: "Personal tech blog of Romy Elmaco"
url: "rmx7.github.io"
paginate: 5
markdown: rdiscount
permalink: pretty
exclude: [Gemfile*]

pages_list:
    Home: '/'
    Tech: '/page/tech'
    About: '/page/about'
    Project: '/page/project'
