name: "RMX|7"
description: "Personal tech blog of Romy Elmaco"
url: "rmx7.github.io"
paginate: 5
markdown: rdiscount
permalink: pretty
pygments: true
exclude: [Gemfile*]

pages_list:
	Home: '/'
	Tech: '/tech'
	About: '/about'
	Project: '/project'
	
